package com.winsun.fruitmix.model;

/**
 * Created by Administrator on 2016/9/18.
 */
public enum OperationResultType {

    LOCAL_MEDIA_SHARE_UPLOADING, SUCCEED, NO_NETWORK_EXCEPTION, IO_EXCEPTION, JSON_EXCEPTION, SOCKET_TIMEOUT_EXCEPTION,
    MALFORMED_URL_EXCEPTION, NETWORK_EXCEPTION,FILE_NOT_FOUND_EXCEPTION,SQL_EXCEPTION,UPLOAD_PHOTO_FAILED,NO_CHANGED,
    MEDIA_DATA_CHANGED,MOER_THAN_ONE_STATION
}
