package com.winsun.fruitmix.model;

/**
 * Created by Administrator on 2016/9/18.
 */
public enum OperationResultType {

    SUCCEED, NO_NETWORK_EXCEPTION, IO_EXCEPTION, JSON_EXCEPTION, SOCKET_TIMEOUT_EXCEPTION,
    MALFORMED_URL_EXCEPTION, NETWORK_EXCEPTION, SQL_EXCEPTION, NO_CHANGED,
    MEDIA_DATA_CHANGED, OPERATION_FAIL

}
