package com.winsun.fruitmix.model;

/**
 * Created by Administrator on 2016/9/18.
 */
public enum OperationTargetType {

    LOCAL_USER, REMOTE_USER, REMOTE_MEDIA, LOCAL_MEDIA, REMOTE_MEDIA_SHARE, LOCAL_MEDIA_SHARE,
    LOCAL_MEDIA_COMMENT, REMOTE_MEDIA_COMMENT,REMOTE_TOKEN, REMOTE_DEVICE_ID,LOCAL_MEDIA_IN_CAMERA,
    REMOTE_FILE,REMOTE_FILE_SHARE,DOWNLOADED_FILE,LOCAL_LOGGED_IN_USER

}
