package com.winsun.fruitmix.util;

/**
 * Created by Administrator on 2016/9/18.
 */
public enum OperationResultType {

    LOCAL_MEDIA_SHARE_UPLOADING, SUCCEED, NO_NETWORK_EXCEPTION, IO_EXCEPTION, JSON_EXCEPTION, SOCKET_TIMEOUT_EXCEPTION,
    MALFORMED_URL_EXCEPTION, NETWORK_EXCEPTION,FILE_NOT_FOUND_EXCEPTION,SQL_EXCEPTION,UPLOAD_PHOTO_FAILED

}
